lib/server.js
Convert port to number if typed as string
This is helpful for real apps
Change-Id: I368639b3ba573249c64bb992439fbe010a049945
=> server: Fix port to 443 if ssl enabled or custom string

example/simplest-thing.js
It can used using:
curl -X PUT -H 'Content-Type: application/json' --data '{"on": true }' \
http://localhost:8888/properties/on
This base was helpful to port to alternate runtimes (ie: IoT.js)
More details and demo video at:
https://s-opensource.org/webthing-iotjs/
Change-Id: Ie126c5621b18afd0094ee21b06501b22a726974a
Origin: https://github.com/tizenteam/webthing-node
=> example: Add simplest actuator example

lib/server.js
This issue was observed while playing with GPIO
Change-Id: Ib4e2df5f98060851c755f4f6fc9c036b0895cf5a
=> server: Stop mdns only if already started

.dockerignore, Dockerfile, docker-compose.yml
Usage is straightforward just run:
docker-compose up
On benefit of having docker files in sources,
is that project can be built on reference OS,
and be deployed on any as long as docker is supported.
This could be good also for tracking regressions (using git-bisect ?).
Origin: https://github.com/rzr/webthing-iotjs
Change-Id: I2924036381d441761df5da50cf089020c3b1f501
=> build: Support docker for test or demo

example/multiple-things.js, example/simplest-thing.js, example/single-thing.js, package.json, travis.sh, webthing.js
Now examples can be run from source directory,
NODE_PATH=. node example/simplest-thing
Or script can run from out of tree, when installed using NPM
MODE_PATH=node_modules node node_modules/example/simplest-thing
Then you can build a systemd service,
if you want thing to be active at boot,
some Hints at:
https://s-opensource.org/2018/06/21/webthing-iotjs/
To check module with multiple-things example, just use:
npm start
Change-Id: I32c4c08b9e15c3e25103dc78f90a901f40080fbb
=> Rename index.js to webthing-node.js for import

example/platform/board/artik530.js, example/platform/gpio/gpio-property.js, example/platform/index.js
Based on sysfs GPIO driver
It is located in $module/*.js
to support serverals drivers (wiring, etc)
Change-Id: Ib393bb3f431f7b5bd3a3ce48797cd5ee08e9af49
Origin: https://github.com/rzr/webthing-iotjs
=> example: platform: Add GpioProperty

example/platform/package-lock.json, example/platform/package.json
Using sysfs
Change-Id: I5cb06e6d98a10924bdff1b5988996c610f64081a
=> example: platform: Install gpio module

example/platform/board/play-phat.js
Note that gpio_key could overlap, see later makefile
For more insights check:
https://github.com/rzr/webthing-iotjs/wiki/Sensor
Change-Id: I0de4ace8a21a0592e5e09e692d43aa04ed7488e8
Origin: https://github.com/rzr/webthing-iotjs
Forwarded: https://github.com/mozilla-iot/webthing-node/pull/31
Thanks-to: @Leon-Anavi <leon@anavi.org>
=> example: platform: Add play-phat board

example/platform/board/flex-phat.js
Usage:
node example/platform flex-phat
For more insights check:
https://github.com/rzr/webthing-iotjs/wiki/Sensor
Thanks-to: @Leon-Anavi <leon@anavi.org>
Change-Id: I3612e28ae50d5bd14f5f4b06c5e0dbead7a84a92
Origin: https://github.com/rzr/webthing-iotjs
Forwarded: https://github.com/mozilla-iot/webthing-node/pull/31
=> example: platform: Add flex-phat board

example/platform/Makefile
To setup GPIOs, it will be used also for IoT.js
Usage:
```
make -C example/platform/ flex-phat
log: board: flex-phat: Loading
Usage:
/home/pi/.nvm/versions/node/v8.11.3/bin/node /tmp/pi/mnt/local/local/home/philippe/var/cache/url/git/ssh/github.com/tizenteam/webthing-node/src/webthing-node/example/platform/index [board] [port]
Try:
curl -H "Accept: application/json" http://localhost:8888
log: board: flex-phat: Started
log: GPIO: GreenLED: open:
log: GPIO: BlueLED: open:
log: GPIO: Relay: open:
log: GPIO: RedLED: open:
log: GPIO: Button: open:
log: GPIO: GPIO23: open:
log: GPIO: Button: change: false
log: GPIO: Button: change: true
log: GPIO: RedLED: writing: true
log: GPIO: GreenLED: writing: true
log: GPIO: Relay: close:
log: GPIO: BlueLED: close:
log: GPIO: GreenLED: close:
log: GPIO: …
```
=> example: platform: Add Makefile helper

example/platform/adc/adc-property.js, example/platform/adc/index.js, example/platform/board/artik530.js
To abstract different ADC or sysfs API,
Note: later this class could land later in separate project
(ie: gpio, iotjs-node? sysfs-node?)
but since it's trivial let's share it here.
Relate-to: https://github.com/EnotionZ/gpio/pull/53
Change-Id: I923159901d3af3e1990ccf3e1510d561c2e0783b
=> adc: Add Adc class

example/platform/Makefile
A way to use generic npm's gpio until supporting wiringpi module
Relate-to: https://github.com/TizenTeam/webthing-iotjs/wiki/Sensors
Change-Id: I2604a16448439b52c6b68ea3639537730320ff9a
=> example: build: Prepare Pi for traffic-phat

example/platform/gpio/gpio-property.js
Really small improvement,
but since some gpio libs are using numbers (0/1)
it's safer this way.
Change-Id: Ib663e95e5dfaffb06853165cccc8e82f9c1e9dc7
=> platform: gpio: Cast to boolean if type mismatch

example/platform/package-lock.json, package-lock.json
This should have been done earlier,
but let's do it now before bumping to 0.8.2 or 0.9.0 ?
Then webthing-iotjs will be released on it.
Change-Id: Ic956ae7d9743d9e7e2d29192d59441d2cf75a3f2
Origin: https://github.com/TizenTeam/webthing-node
=> npm: Freeze deps before version update

lib/server.js
Host names are case insensitive, so store and compare them in lower case.
=> Use case insensitive verification for host name

index.js
This will help iotjs or configurations ignoring package.json's main field.
The source can be cloned and used from runtime's PATH.
Change-Id: I7cfcc0494650be8e41619f9d527ab712a58ef15d
=> Add index.js as fallback to npm's main

docker-compose.yml
Other folder may not be shared,
It has been tested on ARTIK710
Change-Id: Ia97d2aefef1dee4746e85e4fdbe0d72db8fbda4f
=> docker: Export sysfs for gpio and use host mode

docker-compose.yml
I was upstream of this file, so it's fine.
Change-Id: I4d72b4c3a9b8246965c8b1bf7d628308ab6ba48c
=> docker: Align license to upstream project (MPL-2.0)

example/platform/pwm/pwm-property.js
It was tested on Intel Edison PWM0 (50 Hz on buzzer)
Note that GPIO12 must be manually configured first, using:
```sh
gpio=12
echo $gpio | sudo tee -a /sys/class/gpio/export
echo out | sudo tee /sys/class/gpio/gpio$gpio/direction
echo mode1 | sudo tee /sys/kernel/debug/gpio_debug/gpio${gpio}/current_pinmux
```
More/Better gpio drivers maybe added later,
for the record 'pwm' one was prefered here
as base for webthing-iotjs (API to be aligned with IoT.js),
but pwm module is lacking muxing support.
It can be used to control servo motors, for more check:
https://social.samsunginter.net/@rzr/102343690505588635#
Relate-to: https://github.com/djdeath/pwm/issues/2
Change-Id: Ia54efc1d3ef232a831e46f324b9f582a772fceec
=> platform: Add PWM property with variable cycle

example/platform/board/edison.js
It was tested on Intel edison on PWM0
GPIO12 must be manually configured first
using:
```sh
gpio=12
echo $gpio | sudo tee -a /sys/class/gpio/export
echo out | sudo tee /sys/class/gpio/gpio$gpio/direction
echo mode1 | sudo tee /sys/kernel/debug/gpio_debug/gpio${gpio}/current_pinmux
```
More insights at:
https://github.com/rzr/webthing-iotjs/wiki/Actuator
Relate-to: https://github.com/rzr/webthing-iotjs/issues/3
Change-Id: I6f587a840e8c429d91ba2491e7cddfdfab66bf4b
=> platform: Add Edison board to test PWM

Makefile
Is upstreamed from webthing-iotjs
Change-Id: I939f4ba677c4f5d92a5c2a3e40e5ad4238799911
=> build: Add make lint helper

example/platform/adc/index.js
There was a bug when using multiple instances.
It was tested on ARTIK1020
Relate-to: https://github.com/mozilla-iot/webthing-node/pull/49
Change-Id: Idbb9d0f53fc1534407657c9b63a29db50297ae88
=> plaform: Refactor ADC module as class

example/platform/board/artik1020.js
Only ADC has been tested yet, other GPIO and PWM
can be added if needed like other ARTIK520 board.
Relate-to: https://github.com/mozilla-iot/webthing-node/pull/30
Change-Id: I71bb9f06910ece03d3047572a1ddcea78775e54a
=> platform: Add artik1020 to supported boards

example/platform/board/artik1020.js
Note that accessing PWM is requiering write access to sysfs
Add also mapping info.
Relate-to: https://developer.artik.io/documentation/developer-guide/gpio/gpio-mapping.html
Change-Id: Ib6d4592d96a0d0fbe089b6d4b09ec216f2215ce6
=> platform: Add PWM support to artik1020

example/platform/index.js
This can be helpful for IoT.js
that would use a launcher script that
include script and run it later.
Change-Id: I8e5076f84a206b8e28ee0139b88a1dd6c844ee8a
=> platform: Start app only if main script

example/multiple-things.js, example/single-thing.js
Along editor hints.
The reason of doing this, is because aframe-webthing (MPL-2.0)
is seding thoses files to use level instead of brighness.
Change-Id: I681a95037941c7aa13596d8080b3d544166b39ab
=> example: Add licence mini-header
