- README.md
- example/multiple-things.js
- example/single-thing.js
- index.js
- lib/property.js
- lib/server.js
- lib/value.js
- package.json
This adds a Value type to properties, which makes it possible to
listen for external value changes (set the "on" property of a light
to "true") and for sensors to report an updated value.
Fixes #7
> Add observable values to properties.

- package.json
Change-Id: I0ed52b3f8d28716f53fbdf690e7179f27b47337d
> build: Add start script for demo app

- lib/server.js
- lib/utils.js
- package-lock.json
- package.json
- travis.sh
> Fix errors with IP address.

- Dockerfile
- package.json
To be used from docker
Change-Id: I149352dde4afa0a65e1ec88e52adf0e2296310dd
> npm: Add simplest thing

- docker-compose.yml
Change-Id: Ibaa138d19c3b9daee03b384f5b1b015e8472e21f
> docker: docker-compose use entrypoint too for commands

- example/platform/package.json
Fix an export issue if already exported
Relate-to: https://github.com/EnotionZ/GpiO/pull/50
Change-Id: Ib05a7f9d6672c4f0f8ae435e4ac7007cb4a4c0ef
> build: Update gpio node module

- Makefile
- package.json
More feature to come,
to be also used by IoT.js as alternative to npm
Change-Id: I3ed4e65816d67f6d124baabf85151e1b4e5b386f
> build: Add makefile helper for test

- example/platform/adc/adc-property.js
- example/platform/gpio/gpio-property.js
Use self instead of _this generated by babel.js for IoT.js
Now, it's more aligned with ADC class.
Change-Id: I53a9d97f645be63d33e942706105ffbc7ddc0d46
> gpio: Some minor refactoring and fixes

- example/platform/board/artik530.js
Change-Id: Ibfac5db43d864a5d1c75cd390080c6243e8e19a8
> artik: Define GPIO as true for released buttons

- example/platform/board/artik530.js
- example/platform/board/flex-phat.js
- example/platform/board/play-phat.js
Change-Id: Ic986d7e3a83e736e734ead6cf24017364804e831
> board: Minor renaming (reserve _this for babel)

- .eslintignore
Change-Id: I6e9c2e66567f39210c26ec7e2ab7f9e1841d76d8
> build: Ignore node_modules for eslint

- example/platform/board/traffic-phat.js
Thanks-to: @leon-anavi
Change-Id: I0b28f52aad705ebff936f46fef23499e051241b2
> example: Add Traffic pHat board

- package.json
Can be used by npm or docker:
```
time docker build -t "${USER}/${project}" .
docker run -t "${USER}/${project}" node example/simplest-thing.js
```
Change-Id: I8516cedae521ebabd918170c812fe4dc629b4c77
> npm: Add node rule to run any script

- example/platform/adc/adc-property.js
Avoid "self" when "this" can be used
This is failing if not opened
Also improve with cast
Change-Id: I56de0c73117a798f644aba008cbc4361b92c349d
> platform: adc: Fix close if not opened

- example/platform/Makefile
Change-Id: Ifd943f24482acc2a77fb51f20708b4ec12104bfa
> platform: Setup before running boards

- Makefile
To be used for IoT.js, but can also apply to node
Change-Id: I2af51ef62dd90619083d6e15ddd3f72fa242a240
> build: Add helper rules: setup, check, run etc

- .gitignore
Used for temporary files and developer playground
Change-Id: Iab236ff7a68e5c29b6e15d200a82af48837495fd
> build: Ignore tmp folder used for build scripts

- package-lock.json
It was verified using:
```
docker-compose up
web_1  | > webthing@0.8.1 start /usr/local/webthing-node/webthing-node
web_1  | > NODE_PATH=. node example/multiple-things
web_1  |
web_1  | setting new humidity level: 5.322677954298458
```
Change-Id: I0df11bb69e2b60fcc7de234e0944c4093c30b86e
> build: Update dependencies

- Makefile
Change-Id: I9a9b49da970fbc8d381da4110d8b1197badd9ccf
> build: Generate lock file on npm change

- .eslintignore
Change-Id: I886c1a9c93ed5b4868dfa40cfd6161f9a88ea08d
> build: eslint: Ignore tmp folder too

- README.md
And also link some downstream resources
Change-Id: I4d2bfff2a140d42b77755e7b0fe8b357da984711
> doc: Add githup badge as upstream

- README.md
- example/multiple-things.js
- example/platform/index.js
- example/simplest-thing.js
- example/single-thing.js
- lib/server.js
- package.json
> Return promise on server.stop().

- lib/server.js
> Fix crash when mDNS fails.

- lib/server.js
- lib/thing.js
- lib/utils.js
- package-lock.json
- package.json
This reduces the number of dependencies and just matches the
reported websocket href to the requested host.
> Simplify IP address logic.

- CHANGELOG.md
- lib/server.js
- package-lock.json
- package.json
This can be useful when operating behind a proxy, for example.
> Allow user to set a base URL path.

- package-lock.json
- package.json
Relate-to: https://github.com/nodeca/js-yaml/pull/480
Change-Id: Ief98b7475012249b4f8622ee264a042799b59b5e
> npm: Refresh dependencies

- example/platform/board/artik530.js
- example/platform/board/flex-phat.js
- example/platform/board/play-phat.js
- example/platform/board/traffic-phat.js
Change-Id: I583fec1ffb31c4ff9cb80b8ecc7eb149122a3a7a
> platform: Add URI on boards things

- example/platform/index.js
Change-Id: Ic1342ccd8cc105db4ac9fbdccf35910df4d4013d
> platform: Fix declare cleanup before calling it

- example/platform/package.json
Change-Id: I5e947375e86ac13f19de63cdfd53fee5a10d1a72
> platform: Add pwm module to npm manifest

- example/platform/Makefile
Usage:
make -C example/platform edison
Align older rpi related bits
Relate-to: https://github.com/mozilla-iot/webthing-node/pull/99
Change-Id: Id55d10d4385174b8906c2fcf1ab066ebbc37ca2b
> platform: Add helper for edison board

- example/platform/Makefile
Change-Id: Iea78ff7325f8763bb4f53543dee3d95bfdadc8a5
> platfrom: Factorize gpio helper for RPi hats

- example/platform/package-lock.json
- example/platform/package.json
Change-Id: Ie6012c3edf1b2248943dbf1794038e6703fc5a5c
> platform: Install gpio, pwm as optional

- example/platform/Makefile
Change-Id: If4a4342e4c9bb0a8fd22b3370e479c82b30b307e
> platform: Helper to start artik1020 as root

- example/platform/adc/adc-property.js
Change-Id: Ifc8669224b8729fac7acc4e028deabd80b3c15b5
> platform: Fix typo in log

- .gitignore
git: Ignore IoT.js modules
git: Ignore emacs file
Change-Id: I7994b7acdd70b8e3b52a3e1bff88f55ec9c18bbe
> git: Ignore sub runtime modules

- Makefile
Curl will fail on issue
now working again:
Origin: https://github.com/rzr/webthing-iotjs/
Relate-to: https://travis-ci.org/rzr/webthing-iotjs/builds/551839956
Change-Id: I3c1343fc37ac547c00f20f8dbc99c28db5cda74b
> build: Improve test

- lib/server.js
- package.json
> Handle invalid POST to action resources.
